
#
# This R script plots the ancestral chromosome numbers estimated 
# by a ChromoSSE RevBayes analysis.
#


library(ggplot2)
library(RevGadgets)
library(ggtree)



# plot the ancestral states tree generated by RevBayes
p = plot_ancestral_states(tree_file="output/Consenso.tree", 
                          summary_statistic="MAPChromosome", 
                          include_start_states=FALSE, 
                          tip_label_size=3.5, 
                          tip_label_offset=0.002,
                          tip_label_italics=TRUE,
                          node_label_size=3.2,
                          node_label_nudge_x=0.0005,
                          xlim_visible=c(0, 0.05),
                          shoulder_label_size=2,
                          alpha=.3,
                          show_posterior_legend=TRUE,
                          title="Diploid number")

#using ggtree and ggplot2 functions we can now add all sorts of details
# to our figure:

# annotate some of the clades
p = p + geom_cladelabel(node=2, label="Clade A", align=TRUE, offset=0.02, size=2, extend=5)
p = p + geom_cladelabel(node=36, label="Clade B", align=TRUE, offset=0.02, size=2)


# write pdf
print(p)
ggsave("output/Diploid_tucos.pdf")

